{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Budget\",\"BudgetPeriod\",\"Customers\",\"dimProductCategory\",\"Calendar\",\"dimProductSubCategory\",\"Products\",\"Sales\",\"Territory\"]"
      }
    ],
    "culture": "es-NI",
    "cultures": [
      {
        "name": "es-NI",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_a55be2d7-1d01-446c-9536-e2c65b2e4ceb",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Column1",
        "fromTable": "dimProductCategory",
        "toColumn": "Column1",
        "toTable": "dimProductSubCategory"
      },
      {
        "name": "AutoDetected_a894c967-5250-4ce0-a672-7ea607c5dbb5",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Column1",
        "fromTable": "Territory",
        "toColumn": "Column1",
        "toTable": "dimProductSubCategory"
      },
      {
        "name": "AutoDetected_40b23fd2-b2a6-459f-a5e0-1a87e4fb6f17",
        "fromColumn": "CustomerKey",
        "fromTable": "Sales",
        "toColumn": "CustomerKey",
        "toTable": "Customers"
      },
      {
        "name": "AutoDetected_fc6387b1-a01b-4fb7-bc14-606d28685945",
        "fromColumn": "ProductKey",
        "fromTable": "Sales",
        "toColumn": "ProductKey",
        "toTable": "Products"
      }
    ],
    "sourceQueryCulture": "es-NI",
    "tables": [
      {
        "name": "Budget",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1525dfd3-f4da-48e6-8dd3-7276bdfb5117",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83983a44-8607-4206-bd63-326367aa7469",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6631ad5f-24dd-4447-8206-8c331608ff03",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b4c5c733-9864-415f-ac91-0de379dec90c",
        "partitions": [
          {
            "name": "Budget",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = PowerPlatform.Dataflows(null),",
                "    Workspaces = Origen{[Id=\"Workspaces\"]}[Data],",
                "    #\"2df341fb-8872-49e3-a06d-321c2fb40639\" = Workspaces{[workspaceId=\"2df341fb-8872-49e3-a06d-321c2fb40639\"]}[Data],",
                "    #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\" = #\"2df341fb-8872-49e3-a06d-321c2fb40639\"{[dataflowId=\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"]}[Data],",
                "    Budget_ = #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"{[entity=\"Budget\",version=\"\"]}[Data]",
                "in",
                "    Budget_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BudgetPeriod",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1fb5187-67b1-4299-bef1-03f019652d2d",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3525830d-801e-4102-b3df-eac1e6bb6e7b",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e3d1832-91b9-40e7-bfa7-27d5be7701d1",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5d1ab72-56ed-459d-9e8b-6b2aede60b20",
            "sourceColumn": "Column4",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1c4b774b-e5d3-4a18-88f6-2a091a321e4a",
        "partitions": [
          {
            "name": "BudgetPeriod",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = PowerPlatform.Dataflows(null),",
                "    Workspaces = Origen{[Id=\"Workspaces\"]}[Data],",
                "    #\"2df341fb-8872-49e3-a06d-321c2fb40639\" = Workspaces{[workspaceId=\"2df341fb-8872-49e3-a06d-321c2fb40639\"]}[Data],",
                "    #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\" = #\"2df341fb-8872-49e3-a06d-321c2fb40639\"{[dataflowId=\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"]}[Data],",
                "    BudgetPeriod_ = #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"{[entity=\"BudgetPeriod\",version=\"\"]}[Data]",
                "in",
                "    BudgetPeriod_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c8b83970-77c1-4409-a1a9-39e0eb282f29",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea77f6ee-fed9-4d03-ab9f-851b00c8c105",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cf6c7af-a3da-442d-9c9f-e9cdd0804b7f",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3b3d3a45-50fa-4de8-876b-5d2593304a41",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none"
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2f27067-b891-42c3-a8b5-d31eebe22eac",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb17a291-c651-410e-9e8c-217ef3e4e7ce",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14323359-9678-4f87-8d6a-24141206e152",
            "sourceColumn": "YearlyIncome",
            "summarizeBy": "none"
          },
          {
            "name": "NumberChildrenAtHome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e1b2a98-1e32-4aa7-ad37-0d5b2ac1a888",
            "sourceColumn": "NumberChildrenAtHome",
            "summarizeBy": "none"
          },
          {
            "name": "Occupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27c31470-cd94-4837-90fc-af4b0f1f38ca",
            "sourceColumn": "Occupation",
            "summarizeBy": "none"
          },
          {
            "name": "HouseOwnerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a66d032-8a2b-42de-929a-543117f6d36f",
            "sourceColumn": "HouseOwnerFlag",
            "summarizeBy": "none"
          },
          {
            "name": "NumberCarsOwned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27f5ecd5-296a-4107-88bb-497cbce08351",
            "sourceColumn": "NumberCarsOwned",
            "summarizeBy": "none"
          },
          {
            "name": "AddressLine1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c60a5b4f-640a-45c7-8274-dd0dbc290410",
            "sourceColumn": "AddressLine1",
            "summarizeBy": "none"
          },
          {
            "name": "AddressLine2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e2c7b9a-2d0f-458f-89bb-b927eb4c01eb",
            "sourceColumn": "AddressLine2",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c8f7985-0efa-44ee-8ea7-fedfc54b09d1",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "DateFirstPurchase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2615c497-d18c-4b29-8f8f-591370a1a59a",
            "sourceColumn": "DateFirstPurchase",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b6bb5d31-9898-4970-8eaf-993db1248cf2",
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = PowerPlatform.Dataflows(null),",
                "    Workspaces = Origen{[Id=\"Workspaces\"]}[Data],",
                "    #\"2df341fb-8872-49e3-a06d-321c2fb40639\" = Workspaces{[workspaceId=\"2df341fb-8872-49e3-a06d-321c2fb40639\"]}[Data],",
                "    #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\" = #\"2df341fb-8872-49e3-a06d-321c2fb40639\"{[dataflowId=\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"]}[Data],",
                "    Customers_ = #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"{[entity=\"Customers\",version=\"\"]}[Data]",
                "in",
                "    Customers_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dimProductCategory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "902c1e38-aedb-4540-add3-7273508e9eae",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bddbbc6d-8d57-481f-96fd-c48a7523a999",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "419f293b-100f-4d5c-8660-f65c24bb2988",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa1ea117-f689-4c5c-b339-55bc3722330d",
            "sourceColumn": "Column4",
            "summarizeBy": "none"
          },
          {
            "name": "Column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b647ade5-00fe-4059-9488-5145df43050f",
            "sourceColumn": "Column5",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "91e82c94-a4bb-4d48-908b-b939279d9836",
        "partitions": [
          {
            "name": "dimProductCategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = PowerPlatform.Dataflows(null),",
                "    Workspaces = Origen{[Id=\"Workspaces\"]}[Data],",
                "    #\"2df341fb-8872-49e3-a06d-321c2fb40639\" = Workspaces{[workspaceId=\"2df341fb-8872-49e3-a06d-321c2fb40639\"]}[Data],",
                "    #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\" = #\"2df341fb-8872-49e3-a06d-321c2fb40639\"{[dataflowId=\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"]}[Data],",
                "    dimProductCategory_ = #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"{[entity=\"dimProductCategory\",version=\"\"]}[Data]",
                "in",
                "    dimProductCategory_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "310b849c-c07f-44ae-8d07-20510a3c8a6f",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b9082fc9-d626-4ccb-8b7c-a8af6e18ca40",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "DayNumberOfWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "268189a1-4f32-41c2-b3d6-d369f53ad061",
            "sourceColumn": "DayNumberOfWeek",
            "summarizeBy": "sum"
          },
          {
            "name": "DayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40145561-dd03-4011-9d68-2eb876082a34",
            "sourceColumn": "DayName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81f84d04-75da-4237-8555-36c9904582ad",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumberOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f2631aa6-4e3b-408c-9ae4-74ed52916742",
            "sourceColumn": "MonthNumberOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "DayNumberOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "427deba8-36df-4270-9088-88269b757213",
            "sourceColumn": "DayNumberOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekNumberOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3961c15d-aff4-4e38-947d-40ce05cfc706",
            "sourceColumn": "WeekNumberOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd5c1c32-d312-4d4d-bab6-185add5cf56e",
            "sourceColumn": "CalendarQuarter",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd9ca7e8-34c2-4a4e-8190-fae083bf428d",
            "sourceColumn": "CalendarYear",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5a96bb9b-d320-4f83-bd37-9a33ef59b94f",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "02d59c05-e52d-4d8a-bcbc-57696a49052f",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "sum"
          },
          {
            "name": "DayNumberOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a7da6ec9-3731-462d-a78a-c06cf65df07e",
            "sourceColumn": "DayNumberOfMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalSemester",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "54131a79-d584-4578-8311-5fd9050ddf0a",
            "sourceColumn": "FiscalSemester",
            "summarizeBy": "sum"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cf4d353a-ac11-440a-b35f-bc59f26a8a80",
            "sourceColumn": "Period",
            "summarizeBy": "sum"
          },
          {
            "name": "Month ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac82a4d5-87ec-4fc6-97e1-981e364406b6",
            "sourceColumn": "Month ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "0477f384-189d-4f28-a6e8-ac91078d0cf7",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = PowerPlatform.Dataflows(null),",
                "    Workspaces = Origen{[Id=\"Workspaces\"]}[Data],",
                "    #\"2df341fb-8872-49e3-a06d-321c2fb40639\" = Workspaces{[workspaceId=\"2df341fb-8872-49e3-a06d-321c2fb40639\"]}[Data],",
                "    #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\" = #\"2df341fb-8872-49e3-a06d-321c2fb40639\"{[dataflowId=\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"]}[Data],",
                "    Calendar_ = #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"{[entity=\"Calendar\",version=\"\"]}[Data]",
                "in",
                "    Calendar_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dimProductSubCategory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "185ab561-f150-450d-b30f-0014e23383d5",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c35f2400-d7e6-42fd-8210-aaf70ff02fe3",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4edb543f-5886-4635-947c-43dcd1cf572e",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2673006-845e-4cd5-b53d-5ff6756686d6",
            "sourceColumn": "Column4",
            "summarizeBy": "none"
          },
          {
            "name": "Column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f0db530-bcb4-41fb-8846-2ef2adda7a08",
            "sourceColumn": "Column5",
            "summarizeBy": "none"
          },
          {
            "name": "Column6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dc29512-c65a-4ac7-908d-ef42aec1d384",
            "sourceColumn": "Column6",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9466f110-1e8c-4de8-a1a0-7e8226ef7db0",
        "partitions": [
          {
            "name": "dimProductSubCategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = PowerPlatform.Dataflows(null),",
                "    Workspaces = Origen{[Id=\"Workspaces\"]}[Data],",
                "    #\"2df341fb-8872-49e3-a06d-321c2fb40639\" = Workspaces{[workspaceId=\"2df341fb-8872-49e3-a06d-321c2fb40639\"]}[Data],",
                "    #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\" = #\"2df341fb-8872-49e3-a06d-321c2fb40639\"{[dataflowId=\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"]}[Data],",
                "    dimProductSubCategory_ = #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"{[entity=\"dimProductSubCategory\",version=\"\"]}[Data]",
                "in",
                "    dimProductSubCategory_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Products",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7a29c0db-1f2d-4db7-a5a7-6a32dcbd1f39",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec491d8b-307d-438e-9970-61d60b510373",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42ceb7d4-76d8-4910-a444-fa21565426d4",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "StandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3c62a722-f37d-4373-a842-085a0108199d",
            "sourceColumn": "StandardCost",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6f0ebc5-efce-46b5-bff4-0f1806faeda5",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "SafetyStockLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2ea8d4a9-27d7-4ea7-99d2-246817678a63",
            "sourceColumn": "SafetyStockLevel",
            "summarizeBy": "none"
          },
          {
            "name": "ListPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "01d2af5d-851b-4dbe-af8e-7293a55a2ac1",
            "sourceColumn": "ListPrice",
            "summarizeBy": "none"
          },
          {
            "name": "Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c2e31db1-68f6-4dde-a676-892743b1fdc2",
            "sourceColumn": "Size",
            "summarizeBy": "none"
          },
          {
            "name": "SizeRange",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62dd70d7-9013-45d9-9a5f-7c919af659b8",
            "sourceColumn": "SizeRange",
            "summarizeBy": "none"
          },
          {
            "name": "Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c7e85228-e52f-4553-bc31-10962c7c797d",
            "sourceColumn": "Weight",
            "summarizeBy": "none"
          },
          {
            "name": "DaysToManufacture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a7ead35e-7a06-499b-b3b0-18fbabff7cef",
            "sourceColumn": "DaysToManufacture",
            "summarizeBy": "none"
          },
          {
            "name": "ProductLine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b6218db-9b77-45dc-9ab2-97ba2c794b48",
            "sourceColumn": "ProductLine",
            "summarizeBy": "none"
          },
          {
            "name": "DealerPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d989cfbf-eed6-4edc-bef2-52637ff59721",
            "sourceColumn": "DealerPrice",
            "summarizeBy": "none"
          },
          {
            "name": "Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fb177c2-c946-46f5-8c3e-926e08822d56",
            "sourceColumn": "Class",
            "summarizeBy": "none"
          },
          {
            "name": "ModelName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb617371-df21-45ee-aca4-59eb454a03e9",
            "sourceColumn": "ModelName",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10a60451-53ac-4705-9552-5732ed713b9f",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6ceeff8-1fe5-4fc1-9f02-d2842afb67b2",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "SubCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3562ec21-8015-49fc-a4a6-b622422affc1",
            "sourceColumn": "SubCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3961d6b-1c6f-4f37-976d-ad72bf3bd7b5",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9a0953be-1c71-40d7-bed5-439d35d5cd83",
            "sourceColumn": "StartDate",
            "summarizeBy": "none"
          },
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3b6d6a85-0b36-4c3f-903e-ff8fdcf73e2a",
            "sourceColumn": "EndDate",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3fd7c151-e89f-4bfc-ae98-a17ca85f2a47",
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = PowerPlatform.Dataflows(null),",
                "    Workspaces = Origen{[Id=\"Workspaces\"]}[Data],",
                "    #\"2df341fb-8872-49e3-a06d-321c2fb40639\" = Workspaces{[workspaceId=\"2df341fb-8872-49e3-a06d-321c2fb40639\"]}[Data],",
                "    #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\" = #\"2df341fb-8872-49e3-a06d-321c2fb40639\"{[dataflowId=\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"]}[Data],",
                "    Products_ = #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"{[entity=\"Products\",version=\"\"]}[Data]",
                "in",
                "    Products_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5ed1f8b7-ef18-493f-a51a-e3fe9a7ef8c2",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "480a909b-ff46-470e-89bf-ef851e9fc2ad",
            "sourceColumn": "OrderDate Key",
            "summarizeBy": "count"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48431574-e51c-4608-895a-61cf250a5330",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "61f3436f-b40d-4c8e-8d62-eef2c48e6a30",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "37b0aa3a-af34-4de0-8a83-c6959f86fa6d",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "count"
          },
          {
            "name": "SalesOrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ab14cf9-aa05-460e-9037-90faf23cb3f3",
            "sourceColumn": "SalesOrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderLineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78982f7f-82cf-4988-ba6a-fa96f3ee9b31",
            "sourceColumn": "SalesOrderLineNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bafb691e-5dde-4207-b58c-dd440d42818b",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d7cf9b04-18a3-4485-a439-84a26b2c1db8",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "ExtendedAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70eb51b7-6920-4dbd-b696-de6961298a36",
            "sourceColumn": "ExtendedAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPriceDiscountPct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92d92994-c0dc-453c-8bbf-e02067ecc2cf",
            "sourceColumn": "UnitPriceDiscountPct",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3bbcedf1-cf09-41e3-917a-b4ef1ef4b6ed",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductStandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d8c97d4-d239-464b-a9aa-60419ea4c918",
            "sourceColumn": "ProductStandardCost",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "baa85c86-3e70-4db6-b80d-e3f2a8a2b909",
            "sourceColumn": "TotalProductCost",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "319ddf5e-87e5-4b8f-8bf5-4c036420bd64",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "TaxAmt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "901595e6-81b4-4db7-ad12-df116d971e6a",
            "sourceColumn": "TaxAmt",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7220041e-60ec-4d3a-87f3-4508b840d971",
            "sourceColumn": "Freight",
            "summarizeBy": "sum"
          },
          {
            "name": "RegionMonthID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c358c7e8-1e41-48c6-8dce-383fe35d56b7",
            "sourceColumn": "RegionMonthID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9127e246-abee-4905-a199-b2769272cd3f",
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = PowerPlatform.Dataflows(null),",
                "    Workspaces = Origen{[Id=\"Workspaces\"]}[Data],",
                "    #\"2df341fb-8872-49e3-a06d-321c2fb40639\" = Workspaces{[workspaceId=\"2df341fb-8872-49e3-a06d-321c2fb40639\"]}[Data],",
                "    #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\" = #\"2df341fb-8872-49e3-a06d-321c2fb40639\"{[dataflowId=\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"]}[Data],",
                "    Sales_ = #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"{[entity=\"Sales\",version=\"\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Sales_, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"OrderDate\", type date}, {\"OrderDate Key\", Int64.Type}, {\"ProductKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"SalesTerritoryKey\", Int64.Type}, {\"SalesOrderNumber\", type text}, {\"SalesOrderLineNumber\", Int64.Type}, {\"OrderQuantity\", Int64.Type}, {\"UnitPrice\", Int64.Type}, {\"ExtendedAmount\", Int64.Type}, {\"UnitPriceDiscountPct\", Int64.Type}, {\"DiscountAmount\", Int64.Type}, {\"ProductStandardCost\", Int64.Type}, {\"TotalProductCost\", Int64.Type}, {\"SalesAmount\", Int64.Type}, {\"TaxAmt\", Int64.Type}, {\"Freight\", Int64.Type}, {\"RegionMonthID\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Territory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f37fc1ac-84d6-405d-bb32-1883f033ce2b",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fef2aa40-13bf-4093-84d9-8e0afe83758e",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1ac60b3-ea5b-4aae-95af-0dbe1f2a6f87",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8095fbc-1339-444f-9886-afd341dd01cb",
            "sourceColumn": "Column4",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "be05068c-479d-427b-97d1-a4ccb125db93",
        "partitions": [
          {
            "name": "Territory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = PowerPlatform.Dataflows(null),",
                "    Workspaces = Origen{[Id=\"Workspaces\"]}[Data],",
                "    #\"2df341fb-8872-49e3-a06d-321c2fb40639\" = Workspaces{[workspaceId=\"2df341fb-8872-49e3-a06d-321c2fb40639\"]}[Data],",
                "    #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\" = #\"2df341fb-8872-49e3-a06d-321c2fb40639\"{[dataflowId=\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"]}[Data],",
                "    Territory_ = #\"b9c8fcd9-6d0a-42f4-9adb-ecee6e728420\"{[entity=\"Territory\",version=\"\"]}[Data]",
                "in",
                "    Territory_"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}